name: Build and Test

on:
  push:
    branches: [main, master]
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install dependencies and build
      run: npm ci
    - name: Run tests
      run: npm test